[0m10:22:33.066920 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000279B4D42A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000279B6C81730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000279B4437680>]}


============================== 10:22:33.072919 | eaa8ee05-ed40-45a1-bced-1bd6369433df ==============================
[0m10:22:33.072919 [info ] [MainThread]: Running with dbt=1.10.1
[0m10:22:33.073920 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\forti\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt build', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:22:33.075217 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\workspaces\jornada-de-dados\workshop-airflow-dbt\1-local-setup\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:22:33.076230 [debug] [MainThread]: Command `dbt build` failed at 10:22:33.076230 after 0.14 seconds
[0m10:22:33.076230 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000279B768D640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000279B798EA20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000279B7CFFCE0>]}
[0m10:22:33.077229 [debug] [MainThread]: Flushing usage events
[0m10:22:33.728219 [debug] [MainThread]: An error was encountered while trying to flush usage events
